name: CI Pipeline (Orchestrator)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "9.0.x"
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  # Quality Gates - All must pass for PR merge
  code-quality:
    name: Code Quality
    uses: ./.github/workflows/code-quality.yml
    with:
      dotnet-version: "9.0.x"

  build-and-test:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.yml
    needs: code-quality
    with:
      dotnet-version: "9.0.x"

  security-scan:
    name: Security Scan
    uses: ./.github/workflows/security-scan.yml
    needs: code-quality
    with:
      dotnet-version: "9.0.x"

  # Final validation - only runs if all quality gates pass
  final-validation:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [code-quality, build-and-test, security-scan]

    steps:
      - name: All checks passed
        run: |
          echo "✅ GitHub Actions checks passed"
          echo "✅ Build successful in Debug and Release"  
          echo "✅ Tests executed"
          echo "✅ Security scan completed"
          echo "🚀  All quality gates passed successfully!"
