name: Code Quality Check

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: "9.0.x"

jobs:
  code-quality:
    name: Code Quality & Format Check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Check code formatting
        run: dotnet format --verify-no-changes --verbosity diagnostic

      - name: Run linting/analyzers
        run: dotnet build --no-restore --configuration Release --verbosity normal
