name: Security Scan

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: "9.0.x"

jobs:
  security-scan:
    name: Security & Dependency Check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Check for vulnerable packages
        run: dotnet list package --vulnerable --include-transitive

      - name: Check for deprecated packages
        run: dotnet list package --deprecated
